### ISSUE TITLE
inim breaks nim CI

### ISSUE THREAD

**Issue by timotheecour** [inim-repl/INim#74] opened 2020-04-24 02:26 UTC
see also recent issues:
* https://github.com/inim-repl/INim/issues/63
* https://github.com/inim-repl/INim/issues/66

now that inim has it's own CI, how come this wasn't flagged?

see logs https://dev.azure.com/nim-lang/255dfe86-e590-40bb-a8a2-3c0295ebdeb1/_apis/build/builds/4608/logs/80

```
2020-04-24T00:28:02.3111036Z [32mPASS: [36mhttps://github.com/johnnovak/illwill C                      [34m (24.26 sec)[0m
2020-04-24T00:28:02.3112092Z [1m[31mFAIL: [36mhttps://github.com/inim-repl/INim C[0m
2020-04-24T00:28:02.3113166Z [1m[36mTest "https://github.com/inim-repl/INim" in category "nimble-packages"[0m
2020-04-24T00:28:02.3114072Z [1m[31mFailure: reBuildFailed[0m
2020-04-24T00:28:02.3114502Z package test failed
2020-04-24T00:28:02.3114829Z $ nimble test
2020-04-24T00:28:02.3115310Z   Executing task test in /home/vsts/work/1/s/pkgstemp/inim/inim.nimble
2020-04-24T00:28:02.3116277Z Hint: used config file '/home/vsts/work/1/s/config/nim.cfg' [Conf]
2020-04-24T00:28:02.3117280Z Hint: used config file '/home/vsts/work/1/s/config/config.nims' [Conf]
2020-04-24T00:28:02.3118292Z Hint: used config file '/home/vsts/work/1/s/pkgstemp/inim/config.nims' [Conf]
2020-04-24T00:28:02.3118850Z Hint: system [Processing]
...

2020-04-24T00:28:02.3145970Z CC: stdlib_colors.nim
2020-04-24T00:28:02.3146320Z CC: stdlib_termios.nim
2020-04-24T00:28:02.3146689Z CC: stdlib_terminal.nim
2020-04-24T00:28:02.3147040Z CC: stdlib_tables.nim
2020-04-24T00:28:02.3147938Z CC: ../../../../../../.nimble/pkgs/noise-0.1.3/noise/wtf8.nim
2020-04-24T00:28:02.3148875Z CC: ../../../../../../.nimble/pkgs/noise-0.1.3/noise/wcwidth.nim
2020-04-24T00:28:02.3149837Z CC: ../../../../../../.nimble/pkgs/noise-0.1.3/noise/basic.nim
2020-04-24T00:28:02.3150768Z CC: ../../../../../../.nimble/pkgs/noise-0.1.3/noise/posixio.nim
2020-04-24T00:28:02.3151795Z CC: ../../../../../../.nimble/pkgs/noise-0.1.3/noise/styler.nim
2020-04-24T00:28:02.3152721Z CC: ../../../../../../.nimble/pkgs/noise-0.1.3/noise/prompt.nim
2020-04-24T00:28:02.3153212Z CC: stdlib_deques.nim
2020-04-24T00:28:02.3154041Z CC: ../../../../../../.nimble/pkgs/noise-0.1.3/noise/killring.nim
2020-04-24T00:28:02.3154969Z CC: ../../../../../../.nimble/pkgs/noise-0.1.3/noise.nim
2020-04-24T00:28:02.3155417Z CC: ../src/inim.nim
2020-04-24T00:28:02.3155763Z CC: test.nim
2020-04-24T00:28:02.3156070Z Hint:  [Link]
2020-04-24T00:28:02.3156928Z Hint: 82077 LOC; 2.027 sec; 95.609MiB peakmem; Debug build; proj: /home/vsts/work/1/s/pkgstemp/inim/tests/test.nim; out: /home/vsts/work/1/s/pkgstemp/inim/tests/test [SuccessX]
2020-04-24T00:28:02.3158495Z Hint: /home/vsts/work/1/s/pkgstemp/inim/tests/test --rcFilePath=/home/vsts/work/1/s/pkgstemp/inim/inim.ini [Exec]
2020-04-24T00:28:02.3168863Z Hint: used config file '/home/vsts/work/1/s/config/nim.cfg' [Conf]
2020-04-24T00:28:02.3169495Z Hint: used config file '/home/vsts/work/1/s/config/config.nims' [Conf]
2020-04-24T00:28:02.3170071Z Hint: used config file '/home/vsts/work/1/s/pkgstemp/inim/config.nims' [Conf]
2020-04-24T00:28:02.3170391Z Hint: system [Processing]
2020-04-24T00:28:02.3170627Z Hint: widestrs [Processing]
2020-04-24T00:28:02.3170851Z Hint: io [Processing]
2020-04-24T00:28:02.3171069Z Hint: test_interface [Processing]
2020-04-24T00:28:02.3172980Z Hint: sugar [Processing]
2020-04-24T00:28:02.3173201Z Hint: macros [Processing]
2020-04-24T00:28:02.3173418Z Hint: typetraits [Processing]
2020-04-24T00:28:02.3173666Z Hint: underscored_calls [Processing]
2020-04-24T00:28:02.3173889Z Hint: os [Processing]
2020-04-24T00:28:02.3174127Z Hint: strutils [Processing]
2020-04-24T00:28:02.3174346Z Hint: parseutils [Processing]
2020-04-24T00:28:02.3174574Z Hint: math [Processing]
2020-04-24T00:28:02.3174782Z Hint: bitops [Processing]
2020-04-24T00:28:02.3175009Z Hint: algorithm [Processing]
2020-04-24T00:28:02.3175225Z Hint: unicode [Processing]
2020-04-24T00:28:02.3175451Z Hint: pathnorm [Processing]
2020-04-24T00:28:02.3175662Z Hint: osseps [Processing]
2020-04-24T00:28:02.3175883Z Hint: posix [Processing]
2020-04-24T00:28:02.3176089Z Hint: times [Processing]
2020-04-24T00:28:02.3176310Z Hint: options [Processing]
2020-04-24T00:28:02.3176676Z Hint: sequtils [Processing]
2020-04-24T00:28:02.3177049Z /home/vsts/work/1/s/pkgstemp/inim/tests/test_interface.nim(2, 8) Error: cannot open file: ansiparse
2020-04-24T00:28:02.3177424Z stack trace: (most recent call last)
2020-04-24T00:28:02.3177695Z /tmp/nimblecache/nimscriptapi.nim(165, 16)
2020-04-24T00:28:02.3177995Z /home/vsts/work/1/s/pkgstemp/inim/inim_27488.nims(25, 8) testTask
2020-04-24T00:28:02.3178395Z /home/vsts/work/1/s/lib/system/nimscript.nim(260, 7) exec
2020-04-24T00:28:02.3179321Z /home/vsts/work/1/s/lib/system/nimscript.nim(260, 7) Error: unhandled exception: FAILED: nim c -f -d:TEST -r tests/test_interface.nim --rcFilePath="$(pwd)/inim.ini" [OSError]
2020-04-24T00:28:02.3180105Z        Tip: 1 messages have been suppressed, use --verbose to show them.
2020-04-24T00:28:02.3180459Z      Error: Exception raised during nimble script execution
2020-04-24T00:28:02.3190277Z 
2020-04-24T00:38:41.0674457Z [32mPASS: [36mhttps://github.com/narimiran/itertools C                    [34m ( 3.28 sec)[0m

```

**Comment by narimiran** [comment] 2020-04-24 07:38
(Commenting just to be notified when this gets fixed)

**Comment by Tangdongle** [comment] 2020-04-24 07:40
@timotheecour I'm not sure sorry. The ansiparse library include uses a github url in the .nimble file 's include section(https://github.com/PMunch/ansiparse). Does this need an extra step to install that dependency if it's by url?

**Comment by Tangdongle** [comment] 2020-04-24 07:40
I don't think the package can't be installed by `nimble install ansiparse`, is that the issue?

**Comment by narimiran** [comment] 2020-04-24 07:55
I'm not sure that the problem is in `ansiparse`.

My wild guess would be that `--rcFilePath=\"$(pwd)/inim.ini\"` in `inim.nimble` might be different than what you get when it is run on Nim's CI. (I haven't investigated, my guess might be completely wrong)

**Comment by Tangdongle** [comment] 2020-04-24 08:01
I'll remove it, I don't think it's actually necessary

**Comment by timotheecour** [comment] 2020-04-24 08:08
@narimiran 
> (Commenting just to be notified when this gets fixed)

you don't have to comment for that, you can click `subscribe`

> My wild guess would be that

that's not the issue. There are 2 distinct issues.
* important_packages.nim has a bug that keeps breaking packages
I've already described this issue here https://github.com/nim-lang/Nim/pull/13868

* inim has another bug after caused by last commit https://github.com/inim-repl/INim/pull/70
after manually fixing above issue, you'll get another, unrelated, failure:
```
nimble test

/private/tmp/d23/INim/tests/test_interface.nim(51) test_interface
/Users/timothee/git_clone/nim/Nim_devel/lib/system/io.nim(407) readLine
/Users/timothee/git_clone/nim/Nim_devel/lib/system/io.nim(141) raiseEOF
Error: unhandled exception: EOF reached [EOFError]
```

**Comment by Tangdongle** [comment] 2020-04-24 08:27
@timotheecour I think it might be related to the stdin/stdout swapping I did in the tests. I'm in favour of  reverting the commit so it doesn't impact the nim CI until I have time to figure out what the real issue is

**Comment by timotheecour** [comment] 2020-04-24 08:30
> I think it might be related to the stdin/stdout swapping I did in the tests

it is. `swapStdin` seems buggy and doesn't work for windows; instead you can simply use osproc.startProcess

> I'm in favour of reverting the commit so it doesn't impact the nim CI until I have time to figure out what the real issue is

I've already disabled `inim` in https://github.com/nim-lang/Nim/pull/14102 which just got merged, but it would be good to re-enable inim in nim CI.

osproc.startProcess should fix those issues.

**Comment by Tangdongle** [comment] 2020-04-24 08:32
Awesome, thanks for that @timotheecour , I'll look look into that. Is there maybe something we we need to configure on the CI for this that's causing these tests to pass compared to the nim CI?

**Comment by timotheecour** [comment] 2020-04-24 08:36
* your CI only runs on ubuntu-latest (https://github.com/inim-repl/INim/blob/master/.github/workflows/nim.yml), so you should run CI on at least osx,windows (and linux like you are)
* the other bug i mentioned is a long-standing issue on important_packages as i explained, but can be worked around (ugly...) but tagging a release after each change that would break above mentioned logic (eg a new dependency)

**Comment by 0atman** [comment] 2020-05-04 08:45
Hi folks, I somehow missed this thread - apologies.

Now that @Tangdongle has reverted #70, is that fixed? We've just merged a PR again, @timotheecour, did that pass your CI? Thank you for being patient with us!

**Comment by timotheecour** [comment] 2020-05-04 10:15
* i think we should keep this issue open until `pkg "inim"` is re-enabled in important_pacakges (right now still commented out); can you make a PR to uncomment it out in Nim? if not, I can do it
* I think reverting https://github.com/inim-repl/INim/pull/75 was fine, because it had correctness issues; but hopefully these can be fixed and those integration tests re-introduced using osproc; https://github.com/nim-lang/Nim/pull/14211 may make some of those tests a tad easier

**Comment by 0atman** [comment] 2020-05-04 10:42
Done. https://github.com/nim-lang/Nim/pull/14215 @timotheecour sorry I made a PR against your fork at first.

**Comment by 0atman** [comment] 2020-05-09 05:03
I think this is solved

**Closed by 0atman** 2020-05-09 05:03 UTC
